apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: control-center
  name: control-center
spec:
  ports:
  - name: "9021"
    port: 9021
    targetPort: 9021
  selector:
    io.kompose.service: control-center
status:
  loadBalancer: {}
