apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: control-center
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: control-center
    spec:
      containers:
      - env:
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: zk-1:22181,zk-2:32181,zk-3:42181
        - name: PORT
          value: "9021"
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: kf-1:19092,kf-2:29092,kf-3:39092
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value: connect:8083
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        image: confluentinc/cp-enterprise-control-center
        name: control-center
        ports:
        - containerPort: 9021
        resources: {}
      restartPolicy: Always
status: {}
