---
# workingdir
version: '2'
services:
  zk-1:
    image: confluentinc/cp-zookeeper:3.2.0-4
    # hostname: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:22888:23888;zk-1:32888:33888;zk-1:42888:43888
    # Not supported /w kcompose
    # network_mode: host
    ports:
      - "22181:22181"
    restart: always

  zk-2:
    image: confluentinc/cp-zookeeper:3.2.0-4
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-2:22888:23888;zk-2:32888:33888;zk-2:42888:43888
    ports:
      - "32181:32181"
    restart: always

  zk-3:
    image: confluentinc/cp-zookeeper:3.2.0-4
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-3:22888:23888;zk-3:32888:33888;zk-3:42888:43888
    ports:
      - "42181:42181"
    restart: always

  kf-1:
    image: confluentinc/cp-kafka:3.2.0-4
    # hostname: broker
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zk-1:22181,zk-2:32181,zk-3:42181'
      KAFKA_ADVERTISED_LISTENERS: SSL://kf-1:19092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    ports:
      - '19092:19092'
      # - '19092:19092'
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets

  kf-2:
    image: confluentinc/cp-kafka:3.2.0-4
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zk-1:22181,zk-2:32181,zk-3:42181'
      KAFKA_ADVERTISED_LISTENERS: SSL://kf-2:29092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker2_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker2_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker2_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    ports:
      - '29092:29092'
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets

  kf-3:
    image: confluentinc/cp-kafka:3.2.0-4
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zk-1:22181,zk-2:32181,zk-3:42181'
      KAFKA_ADVERTISED_LISTENERS: SSL://kf-3:39092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker3_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker3_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker3_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    ports:
      - '39092:39092'
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}:/etc/kafka/secrets

  schema_registry:
    image: confluentinc/cp-schema-registry:3.2.0-4
    # hostname: schema_registry
    depends_on:
      - zk-1
      - zk-2
      - zk-3
      - kf-1
      - kf-2
      - kf-3
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zk-1:22181,zk-2:32181,zk-3:42181'

  connect:
    image: confluentinc/cp-kafka-connect:3.2.0-4
    # hostname: connect
    depends_on:
      - zk-1
      - zk-2
      - zk-3
      - kf-1
      - kf-2
      - kf-3
      - schema_registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kf-1:19092,kf-2:29092,kf-3:39092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_ZOOKEEPER_CONNECT: 'zk-1:22181,zk-2:32181,zk-3:42181'

  control-center:
    image: confluentinc/cp-enterprise-control-center
    hostname: control-center
    depends_on:
      - zk-1
      - zk-2
      - zk-3
      - kf-1
      - kf-2
      - kf-3
      - schema_registry
      - connect
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kf-1:19092,kf-2:29092,kf-3:39092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zk-1:22181,zk-2:32181,zk-3:42181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      PORT: 9021
