apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kf-1
  name: kf-1
spec:
  ports:
  - name: "19092"
    port: 19092
    targetPort: 19092
  selector:
    io.kompose.service: kf-1
status:
  loadBalancer: {}
