apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kf-2
  name: kf-2
spec:
  ports:
  - name: "29092"
    port: 29092
    targetPort: 29092
  selector:
    io.kompose.service: kf-2
status:
  loadBalancer: {}
