apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kf-2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kf-2
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: SSL://kf-2:29092
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
          value: SSL
        - name: KAFKA_SSL_TRUSTSTORE_FILENAME
          value: kafka.broker2.truststore.jks
        - name: KAFKA_SSL_KEY_CREDENTIALS
          value: broker2_sslkey_creds
        - name: KAFKA_SSL_KEYSTORE_CREDENTIALS
          value: broker2_keystore_creds
        - name: KAFKA_SSL_KEYSTORE_FILENAME
          value: kafka.broker2.keystore.jks
        - name: KAFKA_SSL_TRUSTSTORE_CREDENTIALS
          value: broker2_truststore_creds
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-1:22181,zk-2:32181,zk-3:42181
        image: confluentinc/cp-kafka:3.2.0-4
        name: kf-2
        ports:
        - containerPort: 29092
        resources: {}
        volumeMounts:
        - mountPath: /etc/kafka/secrets
          name: kf-2-claim0
      restartPolicy: Always
      volumes:
      - name: kf-2-claim0
        persistentVolumeClaim:
          claimName: kf-2-claim0
status: {}
