apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kf-3
  name: kf-3
spec:
  ports:
  - name: "39092"
    port: 39092
    targetPort: 39092
  selector:
    io.kompose.service: kf-3
status:
  loadBalancer: {}
