apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zk-1
  name: zk-1
spec:
  ports:
  - name: "22181"
    port: 22181
    targetPort: 22181
  selector:
    io.kompose.service: zk-1
status:
  loadBalancer: {}
