apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zk-2
  name: zk-2
spec:
  ports:
  - name: "32181"
    port: 32181
    targetPort: 32181
  selector:
    io.kompose.service: zk-2
status:
  loadBalancer: {}
