apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: zk-2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zk-2
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: zk-2:22888:23888;zk-2:32888:33888;zk-2:42888:43888
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        image: confluentinc/cp-zookeeper:3.2.0-4
        name: zk-2
        ports:
        - containerPort: 32181
        resources: {}
      restartPolicy: Always
status: {}
